[package]
name = "cargo-warp"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo_metadata = "0.18.1"
clap = { version = "4.5.7", features = ["cargo"] }
indicatif = "0.17.8"
owo-colors = "4.0.0"
regex = "1.10.5"
